name: Provision GKE Cluster

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  terraform:
    name: Apply Terraform
    runs-on: ubuntu-latest
    #dump straight secrets to file can create wronng with echo so need dump secret to env first 
    #teraform requires GCP credentials to be in a file
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      KUBERCONFIG: ${{ secrets.KUBECONFIG }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Write GCP credentials to file
      run: echo "${GOOGLE_CREDENTIALS}" > gcp-creds.json

    - name: Write Kubeconfig to file
      run: echo "${KUBERCONFIG}" > kubeconfig.yaml

    - name: Install gke-gcloud-auth-plugin
      run: |
        sudo apt-get update 
        sudo apt-get install -y google-cloud-cli 
        gcloud components install gke-gcloud-auth-plugin
    
    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -var-file="terraform.tfvars"
    
    # - name: set up gke-gcloud-auth-plugin
    #   run: sudo apt-get install google-cloud-cli-gke-gcloud-auth-plugin



    - name: Terraform Apply
      run: terraform apply -auto-approve -var-file="terraform.tfvars"
