name: Provision GKE Cluster

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  terraform:
    name: Apply Terraform
    runs-on: ubuntu-latest
    #dump straight secrets to file can create wronng with echo so need dump secret to env first 
    #teraform requires GCP credentials to be in a file
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      KUBERCONFIG: ${{ secrets.KUBECONFIG }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Write GCP credentials to file
      run: echo "${GOOGLE_CREDENTIALS}" > gcp-creds.json

    - name: Write Kubeconfig to file
      run: echo "${KUBERCONFIG}" > kubeconfig.yaml

    # - name: Install gke-gcloud-auth-pgilugin
    #   run: |
    #     curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
    #     echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
    #     echo "----Added google-cloud-sdk to apt sources list"
    #     sudo apt-get update
    #     echo "----Installed apt-get update" 
    #     sudo apt-get install google-cloud-cli-gke-gcloud-auth-plugin
    #     gcloud components update

    #     # gcloud auth application-default login
    #     gcloud config set container/use_application_default_credentials true
    #     echo "----Installed gke-gcloud-auth-plugin"
        
    #     gke-gcloud-auth-plugin --version
    #     echo "----gke-gcloud-auth-plugin version"
        
    #     cat -n kubeconfig.yaml
    #     echo "----Kubeconfig.yaml file content"
        
    #     mkdir -p ~/.kube
    #     cp ./kubeconfig.yaml ~/.kube/config
    #     cat ~/.kube/config
    #     echo "----~/.kube/config file content"

    #     echo "----Copied kubeconfig to ~/.kube/config"
    #     export KUBECONFIG=~/.kube/config
    #     echo ${KUBECONFIG}
    #     echo "----Set KUBECONFIG environment variable"  

    #     export USE_GKE_GCLOUD_AUTH_PLUGIN=True
    #     echo "----Set USE_GKE_GCLOUD_AUTH_PLUGIN environment variable to True"

    #     kubectl config view --minify --raw
    #     echo "----kubectl config view --minify --raw output"

    #     which gke-gcloud-auth-plugin
    #     echo "----which gke-gcloud-auth-plugin output"


    
    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -var-file="terraform.tfvars"
    
    # - name: set up gke-gcloud-auth-plugin
    #   run: sudo apt-get install google-cloud-cli-gke-gcloud-auth-plugin



    - name: Terraform Apply
      run: terraform apply -auto-approve -var-file="terraform.tfvars"
